
name: racha_racha
description: Com o Racha Racha, você pode dividir facilmente as contas entre amigos e garantir que cada um pague exatamente o que consumiu!

publish_to: 'none'

version: 1.5.6+2

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  go_router: ^7.1.1
  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.1.6
  lottie: ^2.3.2
  social_share: any
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  firebase_core: any
  cloud_firestore: any
  firebase_crashlytics: any
  share_plus: ^10.0.0
  dartz: ^0.10.1

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/app/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/app/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app/icon-android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.4


flutter:

  uses-material-design: true

  assets:
    - assets/lottie/receipt.json
    - assets/lottie/question.json
    - assets/lottie/smartphone.json
    - assets/lottie/register.json
    - assets/images/app/icon.png
    - assets/images/app/splash.png



